### ISSUE TITLE
Optional fields?

### ISSUE THREAD

**Issue by sylbru** [terezka/yaml#10]
Hi!

Is there a way to decode optional fields? Something like [Json.Decode’s `maybe`](https://package.elm-lang.org/packages/elm/json/1.1.3/Json-Decode#maybe)?

**Comment by MaybeJustJames** [comment]
Hi @sylbru!
You might want to consider looking at [this maintained fork](https://package.elm-lang.org/packages/MaybeJustJames/yaml/latest/Yaml-Decode#maybe) or even [`elm-generic`](https://package.elm-lang.org/packages/andre-dietrich/elm-generic/).

However, this package provides [`sometimes`](https://package.elm-lang.org/packages/terezka/yaml/latest/Yaml-Decode#sometimes).

**Comment by sylbru** [comment]
Oh right, didn’t realize `sometimes` was just what I needed, even though it’s explicitly mentioned in the docs…

Thanks for mentioning the other options as well! I’ll consider them if I need to work more with YAML later.
